#!/bin/bash
for i in *.gp
do
	gnuplot "$i"
done
for l in *.eps; do
	base=${l%.*}
	epstopdf "$base"".eps"
	pdfcrop "$base"".pdf"
done
for f in *-crop.pdf
do
	inkscape --without-gui --file="$f" --export-png="${f%-crop.pdf}.png"
done
mogrify -rotate 90 *.png
rm *.pdf
rm *.eps
echo " "
echo "ALL GRAPHS ARE GENERATED IN PNG FORMAT AND CROPPED....."
echo " "
